# Use Node.js image
FROM node:14.17.0-alpine as development

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies 
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 to allow communication to/from the container
EXPOSE 3000

# Command to start 
CMD ["npm", "start"]

